### PR TITLE
Doc(docker): add status badge of docker build

### PR DESCRIPTION
**Pull request by Guillaumebeuzeboc**
display the status of the docker build from dockerhub

### CODE REVIEW

**Comment by UlysseVautier** [comment]
Added instructions

**Review by UlysseVautier — APPROVED** [review]
Check Readme with additional info. If ok merge

**Comment by Guillaumebeuzeboc** [comment]
Redundant info with the README in docker/readme
Either we delete the readme in docker/ either we include it

**Comment by UlysseVautier** [comment]
Ah yes forgot that one, delete one of them. The README on parent folder is most important as it is the first page you see

**Pull request merged**
